apiVersion: v1
kind: Service
metadata:
  name: axoview-api
  namespace: axoview
  labels:
    app.kubernetes.io/name: axoview
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: axoview
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 80
      targetPort: http
